# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhijianzhang/opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhijianzhang/opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp3.3.1-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhijianzhang/opengl/CMakeFiles /Users/zhijianzhang/opengl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhijianzhang/opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Glitter

# Build rule for target.
Glitter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Glitter
.PHONY : Glitter

# fast build rule for target.
Glitter/fast:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/build
.PHONY : Glitter/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f Glitter/Vendor/glfw/CMakeFiles/uninstall.dir/build.make Glitter/Vendor/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f Glitter/Vendor/glfw/src/CMakeFiles/glfw.dir/build.make Glitter/Vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f Glitter/Vendor/assimp/code/CMakeFiles/assimp.dir/build.make Glitter/Vendor/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named Bullet3OpenCL_clew

# Build rule for target.
Bullet3OpenCL_clew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3OpenCL_clew
.PHONY : Bullet3OpenCL_clew

# fast build rule for target.
Bullet3OpenCL_clew/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/Bullet3OpenCL/CMakeFiles/Bullet3OpenCL_clew.dir/build.make Glitter/Vendor/bullet/src/Bullet3OpenCL/CMakeFiles/Bullet3OpenCL_clew.dir/build
.PHONY : Bullet3OpenCL_clew/fast

#=============================================================================
# Target rules for targets named Bullet2FileLoader

# Build rule for target.
Bullet2FileLoader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet2FileLoader
.PHONY : Bullet2FileLoader

# fast build rule for target.
Bullet2FileLoader/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/Bullet3Serialize/Bullet2FileLoader/CMakeFiles/Bullet2FileLoader.dir/build.make Glitter/Vendor/bullet/src/Bullet3Serialize/Bullet2FileLoader/CMakeFiles/Bullet2FileLoader.dir/build
.PHONY : Bullet2FileLoader/fast

#=============================================================================
# Target rules for targets named Bullet3Dynamics

# Build rule for target.
Bullet3Dynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Dynamics
.PHONY : Bullet3Dynamics

# fast build rule for target.
Bullet3Dynamics/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/Bullet3Dynamics/CMakeFiles/Bullet3Dynamics.dir/build.make Glitter/Vendor/bullet/src/Bullet3Dynamics/CMakeFiles/Bullet3Dynamics.dir/build
.PHONY : Bullet3Dynamics/fast

#=============================================================================
# Target rules for targets named Bullet3Collision

# Build rule for target.
Bullet3Collision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Collision
.PHONY : Bullet3Collision

# fast build rule for target.
Bullet3Collision/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/Bullet3Collision/CMakeFiles/Bullet3Collision.dir/build.make Glitter/Vendor/bullet/src/Bullet3Collision/CMakeFiles/Bullet3Collision.dir/build
.PHONY : Bullet3Collision/fast

#=============================================================================
# Target rules for targets named Bullet3Geometry

# Build rule for target.
Bullet3Geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Geometry
.PHONY : Bullet3Geometry

# fast build rule for target.
Bullet3Geometry/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/Bullet3Geometry/CMakeFiles/Bullet3Geometry.dir/build.make Glitter/Vendor/bullet/src/Bullet3Geometry/CMakeFiles/Bullet3Geometry.dir/build
.PHONY : Bullet3Geometry/fast

#=============================================================================
# Target rules for targets named BulletInverseDynamics

# Build rule for target.
BulletInverseDynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletInverseDynamics
.PHONY : BulletInverseDynamics

# fast build rule for target.
BulletInverseDynamics/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/BulletInverseDynamics/CMakeFiles/BulletInverseDynamics.dir/build.make Glitter/Vendor/bullet/src/BulletInverseDynamics/CMakeFiles/BulletInverseDynamics.dir/build
.PHONY : BulletInverseDynamics/fast

#=============================================================================
# Target rules for targets named BulletSoftBody

# Build rule for target.
BulletSoftBody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletSoftBody
.PHONY : BulletSoftBody

# fast build rule for target.
BulletSoftBody/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build.make Glitter/Vendor/bullet/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build
.PHONY : BulletSoftBody/fast

#=============================================================================
# Target rules for targets named BulletCollision

# Build rule for target.
BulletCollision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletCollision
.PHONY : BulletCollision

# fast build rule for target.
BulletCollision/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/BulletCollision/CMakeFiles/BulletCollision.dir/build.make Glitter/Vendor/bullet/src/BulletCollision/CMakeFiles/BulletCollision.dir/build
.PHONY : BulletCollision/fast

#=============================================================================
# Target rules for targets named BulletDynamics

# Build rule for target.
BulletDynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletDynamics
.PHONY : BulletDynamics

# fast build rule for target.
BulletDynamics/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build.make Glitter/Vendor/bullet/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build
.PHONY : BulletDynamics/fast

#=============================================================================
# Target rules for targets named LinearMath

# Build rule for target.
LinearMath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinearMath
.PHONY : LinearMath

# fast build rule for target.
LinearMath/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/LinearMath/CMakeFiles/LinearMath.dir/build.make Glitter/Vendor/bullet/src/LinearMath/CMakeFiles/LinearMath.dir/build
.PHONY : LinearMath/fast

#=============================================================================
# Target rules for targets named Bullet3Common

# Build rule for target.
Bullet3Common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Common
.PHONY : Bullet3Common

# fast build rule for target.
Bullet3Common/fast:
	$(MAKE) -f Glitter/Vendor/bullet/src/Bullet3Common/CMakeFiles/Bullet3Common.dir/build.make Glitter/Vendor/bullet/src/Bullet3Common/CMakeFiles/Bullet3Common.dir/build
.PHONY : Bullet3Common/fast

Glitter/Sources/main.o: Glitter/Sources/main.cpp.o

.PHONY : Glitter/Sources/main.o

# target to build an object file
Glitter/Sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.o
.PHONY : Glitter/Sources/main.cpp.o

Glitter/Sources/main.i: Glitter/Sources/main.cpp.i

.PHONY : Glitter/Sources/main.i

# target to preprocess a source file
Glitter/Sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.i
.PHONY : Glitter/Sources/main.cpp.i

Glitter/Sources/main.s: Glitter/Sources/main.cpp.s

.PHONY : Glitter/Sources/main.s

# target to generate assembly for a file
Glitter/Sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.s
.PHONY : Glitter/Sources/main.cpp.s

Glitter/Sources/shader.o: Glitter/Sources/shader.cpp.o

.PHONY : Glitter/Sources/shader.o

# target to build an object file
Glitter/Sources/shader.cpp.o:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/shader.cpp.o
.PHONY : Glitter/Sources/shader.cpp.o

Glitter/Sources/shader.i: Glitter/Sources/shader.cpp.i

.PHONY : Glitter/Sources/shader.i

# target to preprocess a source file
Glitter/Sources/shader.cpp.i:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/shader.cpp.i
.PHONY : Glitter/Sources/shader.cpp.i

Glitter/Sources/shader.s: Glitter/Sources/shader.cpp.s

.PHONY : Glitter/Sources/shader.s

# target to generate assembly for a file
Glitter/Sources/shader.cpp.s:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/shader.cpp.s
.PHONY : Glitter/Sources/shader.cpp.s

Glitter/Vendor/glad/src/glad.o: Glitter/Vendor/glad/src/glad.c.o

.PHONY : Glitter/Vendor/glad/src/glad.o

# target to build an object file
Glitter/Vendor/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.o
.PHONY : Glitter/Vendor/glad/src/glad.c.o

Glitter/Vendor/glad/src/glad.i: Glitter/Vendor/glad/src/glad.c.i

.PHONY : Glitter/Vendor/glad/src/glad.i

# target to preprocess a source file
Glitter/Vendor/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.i
.PHONY : Glitter/Vendor/glad/src/glad.c.i

Glitter/Vendor/glad/src/glad.s: Glitter/Vendor/glad/src/glad.c.s

.PHONY : Glitter/Vendor/glad/src/glad.s

# target to generate assembly for a file
Glitter/Vendor/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.s
.PHONY : Glitter/Vendor/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... Glitter"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... assimp"
	@echo "... Bullet3OpenCL_clew"
	@echo "... Bullet2FileLoader"
	@echo "... Bullet3Dynamics"
	@echo "... Bullet3Collision"
	@echo "... Bullet3Geometry"
	@echo "... BulletInverseDynamics"
	@echo "... BulletSoftBody"
	@echo "... BulletCollision"
	@echo "... BulletDynamics"
	@echo "... LinearMath"
	@echo "... Bullet3Common"
	@echo "... Glitter/Sources/main.o"
	@echo "... Glitter/Sources/main.i"
	@echo "... Glitter/Sources/main.s"
	@echo "... Glitter/Sources/shader.o"
	@echo "... Glitter/Sources/shader.i"
	@echo "... Glitter/Sources/shader.s"
	@echo "... Glitter/Vendor/glad/src/glad.o"
	@echo "... Glitter/Vendor/glad/src/glad.i"
	@echo "... Glitter/Vendor/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

